name: Noteshow
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  cached_network_image: ^3.4.0
  calendar_date_picker2: ^1.1.5

  connectivity_plus: ^6.0.5
  currency_text_input_formatter: ^2.2.3
  dio: ^5.5.0+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_easyloading: ^3.0.5
  flutter_expandable_fab: ^2.2.0
  flutter_localizations:
    sdk: flutter
  flutter_multi_formatter: ^2.13.0
  flutter_slidable: ^3.1.1
  flutter_svg: ^2.0.10+1
  get_it: ^7.7.0
  go_router: ^14.2.3
  
  http: ^1.2.2
  injectable: ^2.4.4
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.4
  pretty_dio_logger: ^1.4.0
  qr_flutter: ^4.1.0
  sqflite: ^2.3.3+1
  syncfusion_flutter_datepicker: ^26.2.8

dev_dependencies:
  build_runner: ^2.4.11
  injectable_generator: 
  flutter_gen_runner:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
  assets:
    - assets/images/
    - assets/fonts/
    - assets/colors/

flutter_gen:
  output: lib/core/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)
  integrations:
    flutter_svg: true
    fonts: true
  colors:
    inputs:
      - assets/colors/colors.xml